services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    